(function (window) {
  "use strict";

  window.JasonQSiteConfig = {
    i18n: {
      defaultLanguage: "en",
      languages: ["en", "zh-CN"],
      translations: {
        en: {
          "meta.title": "JasonQ | Personal Website",
          "meta.description": "JasonQ builds AI-powered products and enterprise-ready systems across product, design, full-stack engineering, and AI architecture.",
          "site.aria": "JasonQ personal website",
          "home.aria": "About JasonQ",
          "header.aria": "Site header",
          "nav.aria": "Primary navigation",
          "nav.brand": "JasonQ",
          "nav.work": "Work",
          "nav.contact": "Contact",
          "languageToggle.aria": "Switch to Chinese",
          "languageToggle.title": "Switch to Chinese",
          "profile.aria": "JasonQ profile card",
          "profile.avatarAlt": "JasonQ avatar",
          "profile.contactLinksAria": "Profile contact links",
          "profile.githubAria": "Open JasonQ GitHub",
          "profile.emailAria": "Email JasonQ",
          "profile.meta": "Personal Index",
          "profile.eyebrow": "Product-minded AI Builder",
          "profile.name": "JasonQ",
          "profile.intro": "Full-stack and Agent application developer, exploring genuinely useful AI applications that truly solves real-world business problems.",
          "timeline.education.label": "Education",
          "timeline.education.logoAlt": "UNSW logo",
          "timeline.education.name": "UNSW",
          "timeline.education.date": "2023-2025",
          "timeline.education.title": "Master of Artificial Intelligence",
          "timeline.education.copy": "Focused on machine learning, algorithm design, and software development.",
          "timeline.experience.label": "Experience",
          "timeline.experience.logoAlt": "Samsung logo",
          "timeline.experience.name": "Samsung",
          "timeline.experience.date": "2025-Present",
          "timeline.experience.title": "Full-stack Developer",
          "timeline.experience.copy": "Build enterprise automation AI platforms and deliver AI applications for business workflows.",
          "stack.ai": "AI Stack",
          "stack.frontend": "Frontend",
          "stack.backend": "Backend",
          "stack.delivery": "Delivery",
          "profile.skills": "Product Strategy · Interface Design · Full-stack Engineering · Enterprise AI Delivery",
          "profile.viewProjects": "View Projects",
          "scroll.label": "Scroll",
          "project.codezero.aria": "Project 01: CodeZero",
          "project.codezero.visualAria": "CodeZero product demos",
          "project.codezero.badge": "01 / Agentic Engineering Workflow",
          "project.codezero.title": "CodeZero",
          "project.codezero.copy": "Automation Issue -> PRD -> PR.",
          "project.codezero.pointsAria": "CodeZero focus",
          "project.codezero.pointOne": "Plan",
          "project.codezero.pointOneCopy": "Brainstorm-style Skills parse GitHub Issues into structured PRD/Plans with acceptance criteria, risks, file scope, tests, and commands.",
          "project.codezero.pointTwo": "Build",
          "project.codezero.pointTwoCopy": "LangGraph orchestrates resumable approval loops while an AI coding agent implements changes inside a persistent task sandbox.",
          "project.codezero.pointThree": "Ship",
          "project.codezero.pointThreeCopy": "Quality gates run automatically, summarize verification evidence, change notes, and repro steps, then create a reviewable draft PR.",
          "project.codezero.pointFour": "Repo context",
          "project.codezero.pointFourCopy": "Build CodeGraph and Understand Everything for each repository, with separately configurable business Skill/Rule settings that turn domain knowledge and implementation constraints into dedicated engineering context.",
          "project.codezero.issueWindow": "codezero / Issue to Plan",
          "project.codezero.prWindow": "codezero / Plan to PR",
          "project.codezero.codegraphWindow": "codezero / CodeGraph",
          "project.codezero.knowledgeWindow": "codezero / knowledge graph",
          "project.codezero.configWindow": "codezero / business config",
          "project.codezero.repoBoardWindow": "codezero / repository board",
          "project.codezero.homeBoardWindow": "codezero / home board",
          "project.codezero.mediaLoading": "Loading CodeZero...",
          "project.codezero.demoSelectorAria": "CodeZero demo selector",
          "project.codezero.featureSelectorAria": "CodeZero core feature selector",
          "project.codezero.issueAlt": "CodeZero Issue to Plan demo",
          "project.codezero.prAlt": "CodeZero Plan to PR demo",
          "project.codezero.codegraphAlt": "CodeZero CodeGraph screenshot",
          "project.codezero.knowledgeAlt": "CodeZero knowledge graph screenshot",
          "project.codezero.configAlt": "CodeZero business configuration screenshot",
          "project.codezero.repoBoardAlt": "CodeZero repository board screenshot",
          "project.codezero.homeBoardAlt": "CodeZero home board screenshot",
          "project.codezero.demoLink": "Demo",
          "project.codezero.coreLink": "Core features",
          "project.codezero.github": "Github",
          "project.codezero.issueLink": "Issue to Plan",
          "project.codezero.prLink": "Plan to PR",
          "project.codezero.codegraphLink": "CodeGraph",
          "project.codezero.knowledgeLink": "Knowledge graph",
          "project.codezero.configLink": "Business config",
          "project.codezero.repoBoardLink": "Repo board",
          "project.codezero.homeBoardLink": "Home board",
          "project.purrpilot.aria": "Project 02: MeowPilot",
          "project.purrpilot.visualAria": "MeowPilot demo player",
          "project.purrpilot.badge": "02 / Desktop AI Pet",
          "project.purrpilot.title": "MeowPilot",
          "project.purrpilot.copy": "A Mac desktop AI pet for everyday companionship, combining text and voice chat, workday interaction, and social growth.",
          "project.purrpilot.pointsAria": "MeowPilot focus",
          "project.purrpilot.pointOne": "Personal AI pet",
          "project.purrpilot.pointOneCopy": "Own your AI Agent like raising a pet: it quietly accompanies your desktop and wakes with one click, bringing long-term memory, user preference awareness, and multi-task execution.",
          "project.purrpilot.pointTwo": "A2UI Cards",
          "project.purrpilot.pointTwoCopy": "More than text replies. Chat can generate music, video, images, reminders, weather cards, and live status panels.",
          "project.purrpilot.pointThree": "Skill exchange",
          "project.purrpilot.pointThreeCopy": "Build a Skill system that supports Skill exchange between friends and explores AI social experiences.",
          "project.purrpilot.dashboardWindow": "meow-pilot / workspace",
          "project.purrpilot.cardsWindow": "meow-pilot / A2UI Cards",
          "project.purrpilot.skillsWindow": "meow-pilot / Skill Exchange",
          "project.purrpilot.customWindow": "meow-pilot / pet styling",
          "project.purrpilot.quickWindow": "meow-pilot / quick menu",
          "project.purrpilot.mediaLoading": "Loading demo...",
          "project.purrpilot.selectorAria": "MeowPilot demo selector",
          "project.purrpilot.dashboardAlt": "MeowPilot workspace dashboard, usage, memory, Skill, and settings demo",
          "project.purrpilot.cardsAlt": "MeowPilot session, local media, and weather card demo",
          "project.purrpilot.skillsAlt": "MeowPilot friend Skill exchange demo",
          "project.purrpilot.customAlt": "MeowPilot pet styling and custom image studio demo",
          "project.purrpilot.quickAlt": "MeowPilot desktop pet right-click quick menu demo",
          "project.purrpilot.demoLink": "Demo",
          "project.purrpilot.github": "Github",
          "project.purrpilot.dashboardLink": "Workspace",
          "project.purrpilot.cardsLink": "A2UI Cards",
          "project.purrpilot.skillsLink": "Skill Exchange",
          "project.purrpilot.customLink": "Pet Styling",
          "project.purrpilot.quickLink": "Quick Menu",
          "project.quickjump.aria": "Project 03: AI Chat Jump Click",
          "project.quickjump.browserUrl": "gemini.google.com / conversation",
          "project.quickjump.demoWindow": "gemini.google.com",
          "project.quickjump.platformsWindow": "aichatjump.click",
          "project.quickjump.mediaLoading": "Loading preview...",
          "project.quickjump.demoAlt": "AI Chat Jump Click demo",
          "project.quickjump.platformsAlt": "AI Chat Jump Click supported platforms",
          "project.quickjump.geminiPrompt": "How does Gemini compare to GPT-4 in coding tasks?",
          "project.quickjump.geminiSecond": "Generate a React navigation tree component.",
          "project.quickjump.previewLabel": "Hover preview",
          "project.quickjump.previewTitle": "Generate a React navigation tree component.",
          "project.quickjump.platformsAria": "Supported AI platforms",
          "project.quickjump.platformsTitle": "One extension, shared habits across major AI chat products.",
          "project.quickjump.platformsMeta": "Chrome Extension Manifest V3 · local storage · configurable shortcuts",
          "project.quickjump.readmeTag": "Usage guide",
          "project.quickjump.shortcutPrevious": "Previous answer",
          "project.quickjump.shortcutNext": "Next answer",
          "project.quickjump.shortcutMark": "Mark or unmark the current chat",
          "project.quickjump.shortcutSave": "Save a key message to favorites",
          "project.quickjump.helpJump": "Click jump",
          "project.quickjump.helpMark": "Mark",
          "project.quickjump.helpTheme": "Theme",
          "project.quickjump.tabsAria": "AI Chat Jump Click demos",
          "project.quickjump.tabGemini": "Gemini Web",
          "project.quickjump.tabGeminiCopy": "Direct product workflow",
          "project.quickjump.tabPlatforms": "Platforms",
          "project.quickjump.tabPlatformsCopy": "Supported AI sites",
          "project.quickjump.tabUsage": "Usage",
          "project.quickjump.tabUsageCopy": "Shortcuts and help",
          "project.quickjump.badge": "03 / Browser Extension",
          "project.quickjump.title": "AI Chat Jump Click",
          "project.quickjump.titleLineOne": "AI Chat",
          "project.quickjump.titleLineTwo": "Jump Click",
          "project.quickjump.copy": "Preview, jump through, and save your AI conversations.",
          "project.quickjump.featuresAria": "Core features",
          "project.quickjump.featureNav": "Conversation navigation",
          "project.quickjump.featureNavCopy": "Right-side nodes let users jump back to any question without scrolling.",
          "project.quickjump.featureBookmark": "Bookmarks and highlights",
          "project.quickjump.featureBookmarkCopy": "Long press to save important answers and return to them later.",
          "project.quickjump.featureShortcut": "Keyboard support",
          "project.quickjump.featureShortcutCopy": "Alt shortcuts move, mark, hide, and reveal the navigation rail.",
          "project.quickjump.statsAria": "Project traction",
          "project.quickjump.statUsers": "Users",
          "project.quickjump.statRating": "Store rating",
          "project.quickjump.ratingAria": "5.0 out of 5 store rating",
          "project.quickjump.statStars": "GitHub stars",
          "project.quickjump.live": "Website",
          "project.quickjump.platformsLink": "Supported platforms",
          "project.quickjump.demoLink": "Demo",
          "project.quickjump.chrome": "Chrome Store",
          "project.quickjump.edge": "Edge Store",
          "project.quickjump.github": "Github",
          "project.dataclean.aria": "Project 04: Table Data Clean System",
          "project.dataclean.homeWindow": "table-data-clean / product home",
          "project.dataclean.demoWindow": "table-data-clean / demo carousel",
          "project.dataclean.intakeWindow": "table-data-clean / light UI",
          "project.dataclean.processingWindow": "table-data-clean / async processing",
          "project.dataclean.resultWindow": "table-data-clean / result review",
          "project.dataclean.reportWindow": "table-data-clean / report",
          "project.dataclean.modelsWindow": "table-data-clean / model outputs",
          "project.dataclean.architectureWindow": "table-data-clean / architecture",
          "project.dataclean.mediaLoading": "Loading project image...",
          "project.dataclean.demoCarouselAria": "Table Data Clean System demo carousel",
          "project.dataclean.homeAlt": "Table Data Clean System product home screen",
          "project.dataclean.intakeAlt": "Table Data Clean System light home screen",
          "project.dataclean.demoDarkAlt": "Table Data Clean System dark mode home screen",
          "project.dataclean.demoLightAlt": "Table Data Clean System light mode home screen",
          "project.dataclean.processingAlt": "Table Data Clean System asynchronous processing screen",
          "project.dataclean.resultAlt": "Table Data Clean System result search interface",
          "project.dataclean.reportAlt": "Table Data Clean System report screen",
          "project.dataclean.minilmAlt": "MiniLM model result chart",
          "project.dataclean.t5Alt": "T5 model result chart",
          "project.dataclean.architectureAlt": "Table Data Clean System architecture graph",
          "project.dataclean.badge": "04 / Tabular Data AI Cleaning Platform",
          "project.dataclean.title": "Table Data Clean System",
          "project.dataclean.titleLineOne": "Table Data",
          "project.dataclean.titleLineTwo": "Clean System",
          "project.dataclean.copy": "A cleaning platform for messy tables, covering upload, async processing, result review, reports, and model-output visualization.",
          "project.dataclean.featuresAria": "Table Data Clean System focus",
          "project.dataclean.featureFullstack": "Full-stack product delivery",
          "project.dataclean.featureFullstackCopy": "Built the React workflow and backend APIs around upload, task state, result lookup, and report download.",
          "project.dataclean.featureAsync": "Asynchronous job orchestration",
          "project.dataclean.featureAsyncCopy": "Connected FastAPI, Celery, Redis, SQLite, and file storage into a resumable data-cleaning pipeline.",
          "project.dataclean.featureModel": "AI model integration",
          "project.dataclean.featureModelCopy": "Visualizes model evaluation status and final cleaning results through an end-to-end pipeline dashboard.",
          "project.dataclean.statsAria": "Project scope",
          "project.dataclean.statRole": "Role",
          "project.dataclean.statRoleValue": "Full-stack",
          "project.dataclean.statStack": "Stack",
          "project.dataclean.statPipeline": "Pipeline",
          "project.dataclean.statPipelineValue": "Async jobs",
          "project.dataclean.demoLink": "Demo",
          "project.dataclean.homeLink": "Home",
          "project.dataclean.intakeLink": "Light UI",
          "project.dataclean.processingLink": "Processing",
          "project.dataclean.resultLink": "Results",
          "project.dataclean.reportLink": "Report",
          "project.dataclean.modelsLink": "Models",
          "project.dataclean.architectureLink": "Architecture",
          "project.dataclean.github": "Github"
        },
        "zh-CN": {
          "meta.title": "JasonQ | 个人网站",
          "meta.description": "JasonQ 从产品、设计、全栈工程与 AI 架构出发，构建 AI 产品和可在企业场景落地的数字系统。",
          "site.aria": "JasonQ 个人主页",
          "home.aria": "关于 JasonQ",
          "header.aria": "站点头部",
          "nav.aria": "主导航",
          "nav.brand": "JasonQ",
          "nav.work": "作品",
          "nav.contact": "联系",
          "languageToggle.aria": "切换到英文",
          "languageToggle.title": "切换到英文",
          "profile.aria": "JasonQ 个人资料卡",
          "profile.avatarAlt": "JasonQ 头像",
          "profile.contactLinksAria": "个人联系方式",
          "profile.githubAria": "打开 JasonQ 的 GitHub",
          "profile.emailAria": "给 JasonQ 发邮件",
          "profile.meta": "个人主页",
          "profile.eyebrow": "产品型 AI 构建者",
          "profile.name": "JasonQ",
          "profile.intro": "全栈及 Agent 应用开发者, 专注于探索真正能够解决实际问题的 AI 应用",
          "timeline.education.label": "学习",
          "timeline.education.logoAlt": "UNSW 标志",
          "timeline.education.name": "UNSW",
          "timeline.education.date": "2023-2025",
          "timeline.education.title": "Master of AI",
          "timeline.education.copy": "机器学习、算法设计、软件开发。",
          "timeline.experience.label": "经验",
          "timeline.experience.logoAlt": "三星标志",
          "timeline.experience.name": "三星",
          "timeline.experience.date": "2025-至今",
          "timeline.experience.title": "全栈开发",
          "timeline.experience.copy": "企业自动化 AI 平台与应用落地。",
          "stack.ai": "AI 能力",
          "stack.frontend": "前端",
          "stack.backend": "后端",
          "stack.delivery": "交付",
          "profile.skills": "产品策略 · 界面设计 · 全栈工程 · 企业 AI 落地",
          "profile.viewProjects": "查看作品",
          "scroll.label": "下滑",
          "project.codezero.aria": "项目 01：CodeZero",
          "project.codezero.visualAria": "CodeZero 产品演示",
          "project.codezero.badge": "01 / Agentic 工程工作流",
          "project.codezero.title": "CodeZero",
          "project.codezero.copy": "Automation Issue -> PRD -> PR。",
          "project.codezero.pointsAria": "CodeZero 重点",
          "project.codezero.pointOne": "规划",
          "project.codezero.pointOneCopy": "采用 Brainstorm 等 Skill，智能解析 GitHub Issue，生成结构化 PRD/Plan，覆盖验收标准、风险点、影响文件范围、测试项和执行命令等。",
          "project.codezero.pointTwo": "实现",
          "project.codezero.pointTwoCopy": "基于 LangGraph 编排可恢复的审批循环，由 AI Coding Agent 在持久化 task sandbox 中完成代码实现。",
          "project.codezero.pointThree": "交付",
          "project.codezero.pointThreeCopy": "自动运行质量门禁，汇总验证证据、变更说明和复现步骤，并创建可 review 的 draft PR。",
          "project.codezero.pointFour": "仓库上下文",
          "project.codezero.pointFourCopy": "为每个仓库构建 CodeGraph 和 Understand Everything，并可单独配置业务 Skill/Rule，通过业务知识实现约束，构建专属工程上下文。",
          "project.codezero.issueWindow": "codezero / Issue to Plan",
          "project.codezero.prWindow": "codezero / Plan to PR",
          "project.codezero.codegraphWindow": "codezero / CodeGraph",
          "project.codezero.knowledgeWindow": "codezero / 知识图谱",
          "project.codezero.configWindow": "codezero / 具体业务配置",
          "project.codezero.repoBoardWindow": "codezero / 仓库看板",
          "project.codezero.homeBoardWindow": "codezero / 主页看板",
          "project.codezero.mediaLoading": "正在加载 CodeZero...",
          "project.codezero.demoSelectorAria": "CodeZero Demo 选择器",
          "project.codezero.featureSelectorAria": "CodeZero 核心功能选择器",
          "project.codezero.issueAlt": "CodeZero Issue to Plan 演示",
          "project.codezero.prAlt": "CodeZero Plan to PR 演示",
          "project.codezero.codegraphAlt": "CodeZero CodeGraph 截图",
          "project.codezero.knowledgeAlt": "CodeZero 知识图谱截图",
          "project.codezero.configAlt": "CodeZero 具体业务配置截图",
          "project.codezero.repoBoardAlt": "CodeZero 仓库看板截图",
          "project.codezero.homeBoardAlt": "CodeZero 主页看板截图",
          "project.codezero.demoLink": "Demo",
          "project.codezero.coreLink": "核心功能",
          "project.codezero.github": "Github",
          "project.codezero.issueLink": "Issue to Plan",
          "project.codezero.prLink": "Plan to PR",
          "project.codezero.codegraphLink": "CodeGraph",
          "project.codezero.knowledgeLink": "知识图谱",
          "project.codezero.configLink": "具体业务配置",
          "project.codezero.repoBoardLink": "仓库看板",
          "project.codezero.homeBoardLink": "主页看板",
          "project.purrpilot.aria": "项目 02：MeowPilot",
          "project.purrpilot.visualAria": "MeowPilot Demo 播放窗口",
          "project.purrpilot.badge": "02 / 桌面 AI 宠物",
          "project.purrpilot.title": "MeowPilot",
          "project.purrpilot.copy": "陪伴你日常的 Mac 桌面 AI 宠物，集成文字与语音聊天、日常工作交互和社交成长。",
          "project.purrpilot.pointsAria": "MeowPilot 重点",
          "project.purrpilot.pointOne": "专属 AI 宠物",
          "project.purrpilot.pointOneCopy": "像养宠物一样拥有自己的 AI Agent：平时安静陪伴桌面，需要时一键唤醒，具备长期记忆、用户偏好感知与多任务执行能力。",
          "project.purrpilot.pointTwo": "生成式交互卡片",
          "project.purrpilot.pointTwoCopy": "不只是回复文字。聊天过程中可以直接生成音乐、视频、图片、提醒事项、天气卡片和实时状态面板。",
          "project.purrpilot.pointThree": "Skill 交换与成长",
          "project.purrpilot.pointThreeCopy": "构建 Skill 体系，支持与好友间 Skill 交换，探索 AI 社交场景。",
          "project.purrpilot.dashboardWindow": "meow-pilot / 工作台",
          "project.purrpilot.cardsWindow": "meow-pilot / 生成式交互卡片",
          "project.purrpilot.skillsWindow": "meow-pilot / Skill 交换",
          "project.purrpilot.customWindow": "meow-pilot / 宠物造型定制",
          "project.purrpilot.quickWindow": "meow-pilot / 快捷菜单",
          "project.purrpilot.mediaLoading": "正在加载 Demo...",
          "project.purrpilot.selectorAria": "MeowPilot Demo 选择器",
          "project.purrpilot.dashboardAlt": "MeowPilot 工作台、用量、记忆、Skill 与配置切换演示",
          "project.purrpilot.cardsAlt": "MeowPilot 多会话、本地媒体与天气卡片演示",
          "project.purrpilot.skillsAlt": "MeowPilot 好友 Skill 交换演示",
          "project.purrpilot.customAlt": "MeowPilot 宠物造型定制与自定义图片工作室演示",
          "project.purrpilot.quickAlt": "MeowPilot 桌面宠物右键快捷菜单演示",
          "project.purrpilot.demoLink": "Demo",
          "project.purrpilot.github": "Github",
          "project.purrpilot.dashboardLink": "工作台",
          "project.purrpilot.cardsLink": "生成式交互卡片",
          "project.purrpilot.skillsLink": "Skill 交换",
          "project.purrpilot.customLink": "宠物造型定制",
          "project.purrpilot.quickLink": "快捷菜单",
          "project.quickjump.aria": "项目 03：AI Chat Jump Click",
          "project.quickjump.browserUrl": "gemini.google.com / 对话页面",
          "project.quickjump.demoWindow": "gemini.google.com",
          "project.quickjump.platformsWindow": "aichatjump.click",
          "project.quickjump.mediaLoading": "正在加载展示素材...",
          "project.quickjump.demoAlt": "AI Chat Jump Click 功能演示",
          "project.quickjump.platformsAlt": "AI Chat Jump Click 支持平台展示",
          "project.quickjump.geminiPrompt": "Gemini 3 Pro 和 GPT-4 在代码任务上有什么差异？",
          "project.quickjump.geminiSecond": "生成一个 React 对话导航树组件。",
          "project.quickjump.previewLabel": "悬停预览",
          "project.quickjump.previewTitle": "生成一个 React 对话导航树组件。",
          "project.quickjump.platformsAria": "支持的 AI 平台",
          "project.quickjump.platformsTitle": "一个插件，把同一套浏览习惯带到主流 AI 对话产品里。",
          "project.quickjump.platformsMeta": "Chrome Extension Manifest V3 · 本地存储 · 快捷键可配置",
          "project.quickjump.readmeTag": "使用指南",
          "project.quickjump.shortcutPrevious": "上一条回答",
          "project.quickjump.shortcutNext": "下一条回答",
          "project.quickjump.shortcutMark": "标记或取消标记当前对话",
          "project.quickjump.shortcutSave": "把重点消息保存到收藏",
          "project.quickjump.helpJump": "点击跳转",
          "project.quickjump.helpMark": "标记收藏",
          "project.quickjump.helpTheme": "主题切换",
          "project.quickjump.tabsAria": "AI Chat Jump Click 功能演示",
          "project.quickjump.tabGemini": "Gemini 网页端",
          "project.quickjump.tabGeminiCopy": "直接展示真实使用路径",
          "project.quickjump.tabPlatforms": "支持平台",
          "project.quickjump.tabPlatformsCopy": "覆盖主流 AI 站点",
          "project.quickjump.tabUsage": "使用方式",
          "project.quickjump.tabUsageCopy": "快捷键和帮助说明",
          "project.quickjump.badge": "03 / 浏览器插件",
          "project.quickjump.title": "AI Chat Jump Click",
          "project.quickjump.titleLineOne": "AI Chat",
          "project.quickjump.titleLineTwo": "Jump Click",
          "project.quickjump.copy": "快速预览、跳转、收藏你与AI的对话",
          "project.quickjump.featuresAria": "核心功能",
          "project.quickjump.featureNav": "对话导航",
          "project.quickjump.featureNavCopy": "右侧节点对应每一次提问，点击即可回到目标位置。",
          "project.quickjump.featureBookmark": "标记与收藏",
          "project.quickjump.featureBookmarkCopy": "长按保存关键回答，后续可以从收藏列表直接返回。",
          "project.quickjump.featureShortcut": "键盘支持",
          "project.quickjump.featureShortcutCopy": "通过 Alt 快捷键切换、标记、隐藏或唤出导航条。",
          "project.quickjump.statsAria": "项目数据",
          "project.quickjump.statUsers": "用户数",
          "project.quickjump.statRating": "商店评分",
          "project.quickjump.ratingAria": "商店评分 5.0 分，满分 5 分",
          "project.quickjump.statStars": "GitHub 星标",
          "project.quickjump.live": "官方网站",
          "project.quickjump.platformsLink": "支持平台",
          "project.quickjump.demoLink": "Demo",
          "project.quickjump.chrome": "Chrome 商店",
          "project.quickjump.edge": "Edge 商店",
          "project.quickjump.github": "Github",
          "project.dataclean.aria": "项目 04：Table Data Clean System",
          "project.dataclean.homeWindow": "table-data-clean / 产品首页",
          "project.dataclean.demoWindow": "table-data-clean / Demo 轮播",
          "project.dataclean.intakeWindow": "table-data-clean / 浅色界面",
          "project.dataclean.processingWindow": "table-data-clean / 异步处理",
          "project.dataclean.resultWindow": "table-data-clean / 结果查询",
          "project.dataclean.reportWindow": "table-data-clean / 报告页面",
          "project.dataclean.modelsWindow": "table-data-clean / 模型输出",
          "project.dataclean.architectureWindow": "table-data-clean / 系统架构",
          "project.dataclean.mediaLoading": "正在加载项目图片...",
          "project.dataclean.demoCarouselAria": "Table Data Clean System Demo 轮播",
          "project.dataclean.homeAlt": "Table Data Clean System 产品首页",
          "project.dataclean.intakeAlt": "Table Data Clean System 浅色首页",
          "project.dataclean.demoDarkAlt": "Table Data Clean System 暗色首页",
          "project.dataclean.demoLightAlt": "Table Data Clean System 明亮首页",
          "project.dataclean.processingAlt": "Table Data Clean System 异步处理页面",
          "project.dataclean.resultAlt": "Table Data Clean System 结果查询界面",
          "project.dataclean.reportAlt": "Table Data Clean System 报告页面",
          "project.dataclean.minilmAlt": "MiniLM 模型结果图",
          "project.dataclean.t5Alt": "T5 模型结果图",
          "project.dataclean.architectureAlt": "Table Data Clean System 系统架构图",
          "project.dataclean.badge": "04 / 表格数据AI清洗平台",
          "project.dataclean.title": "Table Data Clean System",
          "project.dataclean.titleLineOne": "Table Data",
          "project.dataclean.titleLineTwo": "Clean System",
          "project.dataclean.copy": "面向杂乱表格的数据清洗系统，包括上传、异步任务、结果查询、报告下载与模型输出可视化。",
          "project.dataclean.featuresAria": "Table Data Clean System 项目重点",
          "project.dataclean.featureFullstack": "全栈产品实现",
          "project.dataclean.featureFullstackCopy": "围绕上传、任务状态、结果检索和报告下载，完成 React 工作流与后端 API。",
          "project.dataclean.featureAsync": "异步任务编排",
          "project.dataclean.featureAsyncCopy": "将 FastAPI、Celery、Redis、SQLite 与文件存储串成可恢复的数据清洗流水线。",
          "project.dataclean.featureModel": "AI 模型接入",
          "project.dataclean.featureModelCopy": "可视化展示模型评估状态与最终清洗结果，贯穿数据上传到产出的完整流程。",
          "project.dataclean.statsAria": "项目范围",
          "project.dataclean.statRole": "角色",
          "project.dataclean.statRoleValue": "全栈开发",
          "project.dataclean.statStack": "技术栈",
          "project.dataclean.statPipeline": "流水线",
          "project.dataclean.statPipelineValue": "异步任务",
          "project.dataclean.demoLink": "Demo",
          "project.dataclean.homeLink": "首页",
          "project.dataclean.intakeLink": "浅色界面",
          "project.dataclean.processingLink": "处理",
          "project.dataclean.resultLink": "结果",
          "project.dataclean.reportLink": "报告",
          "project.dataclean.modelsLink": "模型",
          "project.dataclean.architectureLink": "架构",
          "project.dataclean.github": "Github"
        }
      }
    },

    intro: {
      heroImageSelector: ".home-bg",
      initialImageSelectors: [
        ".home-bg",
        ".loader-window__image",
        ".profile-card img"
      ],
      loadedClass: "is-loaded",
      completeClass: "is-intro-complete",
      waitForHeroImage: true,
      imageReadyDelayMs: 180,
      imageTimeoutMs: 2400,
      projectPreloadDelayMs: 360,
      totalDurationMs: 6200
    },

    projects: [
      {
        id: "codezero",
        order: "01/04",
        title: "CodeZero"
      },
      {
        id: "purrpilot",
        order: "02/04",
        title: "MeowPilot"
      },
      {
        id: "aichat-quickjump",
        order: "03/04",
        title: "AI Chat Jump Click"
      },
      {
        id: "table-data-clean",
        order: "04/04",
        title: "Table Data Clean System"
      }
    ]
  };
})(window);
